Importando bibliotecas e dataset

In [94]:
import pandas as pd

df = pd.read_csv("data_cts_intentional_homicide.csv", decimal=",")

Separando os países

In [95]:
countries_df = df[df["Country"] != df["Region"]]
countries_df = countries_df[~countries_df["Country"].str.startswith("All ")]
countries_df = countries_df.query("Age == 'Total' & Dimension == 'Total' & Category == 'Total'")

countries_df

,Iso3_code,Country,Region,Subregion,Indicator,Dimension,Category,Sex,Age,Year,Unit of measurement,VALUE,Source
1308,ABW,Aruba,Americas,Latin America and the Caribbean,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,0.000000,MD
1309,AIA,Anguilla,Americas,Latin America and the Caribbean,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,0.000000,WHO/NSO/SDG/PAHO
1310,ARM,Armenia,Asia,Western Asia,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,178.000000,UNSDC/TransMonEE/CTS/Covid-19/SDG
1311,ATG,Antigua and Barbuda,Americas,Latin America and the Caribbean,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,1.000000,MD/PAHO/OAS/CTS
1312,AUS,Australia,Oceania,Australia and New Zealand,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,374.000000,MD/Eurostat/GSH 2019 Revision/CTS
...,...,...,...,...,...,...,...,...,...,...,...,...,...
112243,GRC,Greece,Europe,Southern Europe,Death due to intentional homicide in prison,Total,Total,Total,Total,2021,"Rate per 100,000 population",0.000000,SDG/CTS
112244,LTU,Lithuania,Europe,Northern Europe,Death due to intentional homicide in prison,Total,Total,Total,Total,2021,"Rate per 100,000 population",0.000000,CTS/SDG
112245,MAC,"China, Macao Special Administrative Region",Asia,Eastern Asia,Death due to intentional homicide in prison,Total,Total,Total,Total,2021,"Rate per 100,000 population",0.000000,SDG/CTS
112246,RUS,Russian Federation,Europe,Eastern Europe,Death due to intentional homicide in prison,Total,Total,Total,Total,2021,"Rate per 100,000 population",0.010338,CTS/SDG
112247,VAT,Holy See,Europe,Southern Europe,Death due to intentional homicide in prison,Total,Total,Total,Total,2021,"Rate per 100,000 population",0.000000,CTS/SDG

Separando as regiões

In [96]:
regions_df = df[df["Country"] == df["Region"]]
#regions_df = regions_df[~regions_df["Country"].str.startswith("All ")]
#regions_df = regions_df[regions_df["Country"].ne("World")]
regions_df = regions_df.query("Age == 'Total' & Dimension == 'Total' & Category == 'Total'")
regions_df

,Iso3_code,Country,Region,Subregion,Indicator,Dimension,Category,Sex,Age,Year,Unit of measurement,VALUE,Source
59612,WORLD,World,World,World,Victims of Intentional Homicide - Regional Est...,Total,Total,Total,Total,2000,Counts,424387.104800,UNODC estimate based on national data
59613,WORLD,World,World,World,Victims of Intentional Homicide - Regional Est...,Total,Total,Total,Total,2001,Counts,435484.333900,UNODC estimate based on national data
59614,WORLD,World,World,World,Victims of Intentional Homicide - Regional Est...,Total,Total,Total,Total,2002,Counts,438760.530200,UNODC estimate based on national data
59615,WORLD,World,World,World,Victims of Intentional Homicide - Regional Est...,Total,Total,Total,Total,2003,Counts,432725.973600,UNODC estimate based on national data
59616,WORLD,World,World,World,Victims of Intentional Homicide - Regional Est...,Total,Total,Total,Total,2004,Counts,423863.789900,UNODC estimate based on national data
...,...,...,...,...,...,...,...,...,...,...,...,...,...
113629,M49_W_EUR,Western Europe,Western Europe,Western Europe,Victims of Intentional Homicide - Regional Est...,Total,Total,Male,Total,2017,"Rate per 100,000 population",1.203212,UNODC estimate based on national data
113630,M49_W_EUR,Western Europe,Western Europe,Western Europe,Victims of Intentional Homicide - Regional Est...,Total,Total,Male,Total,2018,"Rate per 100,000 population",1.200968,UNODC estimate based on national data
113631,M49_W_EUR,Western Europe,Western Europe,Western Europe,Victims of Intentional Homicide - Regional Est...,Total,Total,Male,Total,2019,"Rate per 100,000 population",1.107534,UNODC estimate based on national data
113632,M49_W_EUR,Western Europe,Western Europe,Western Europe,Victims of Intentional Homicide - Regional Est...,Total,Total,Male,Total,2020,"Rate per 100,000 population",1.200102,UNODC estimate based on national data
113633,M49_W_EUR,Western Europe,Western Europe,Western Europe,Victims of Intentional Homicide - Regional Est...,Total,Total,Male,Total,2021,"Rate per 100,000 population",1.148822,UNODC estimate based on national data

Pergunta 1: Quais países apresentam os 10 maiores índices de homicídios nos últimos 5
anos?

In [108]:
most_homicide_count_in_5_years = countries_df.query("Year >= 2018 & Sex == 'Total'")
most_homicide_count_in_5_years = most_homicide_count_in_5_years[most_homicide_count_in_5_years["Indicator"].eq("Victims of intentional homicide")]
most_homicide_count_in_5_years = most_homicide_count_in_5_years[most_homicide_count_in_5_years["Unit of measurement"].eq("Rate per 100,000 population")]
most_homicide_count_in_5_years = most_homicide_count_in_5_years.groupby("Country", as_index=False)["VALUE"].sum().sort_values(by="VALUE", ascending=False)
most_homicide_count_in_5_years.head(10)

                              Country       VALUE
68                            Jamaica  246.189952
60                           Honduras  187.855027
134               Trinidad and Tobago  164.982209
17                             Belize  156.825014
116  Saint Vincent and the Grenadines  153.018399
115                       Saint Lucia  151.229856
85                             Mexico  142.357741
43                        El Salvador  137.816372
11                            Bahamas  124.478151
114             Saint Kitts and Nevis  123.705026

Pergunta 2: Quais países apresentam os 10 maiores índices de homicídios de mulheres em
2022?

In [98]:
most_female_homicides_2022 = countries_df.query("Year == 2022 & Sex == 'Female'")
most_female_homicides_2022 = most_female_homicides_2022[most_female_homicides_2022["Indicator"].eq("Victims of intentional homicide")]
most_female_homicides_2022 = most_female_homicides_2022[most_female_homicides_2022["Unit of measurement"].eq("Rate per 100,000 population")]
most_female_homicides_2022 = most_female_homicides_2022.groupby("Country", as_index=False)["VALUE"].sum()
most_female_homicides_2022 = most_female_homicides_2022.sort_values(by="VALUE", ascending=False)
most_female_homicides_2022.head(10)

                             Country     VALUE
51                       Saint Lucia  9.900010
52  Saint Vincent and the Grenadines  9.800174
31                           Jamaica  8.701764
38                            Mexico  6.014469
6                            Bahamas  4.669264
22                           Ecuador  4.647089
8                             Belize  4.465936
34                            Latvia  4.031317
16                          Colombia  3.810115
59                          Suriname  3.221489

Pergunta 3: Quais as regiões com mais homicídios?

In [99]:
regions_with_most_homicides = regions_df.query("Sex == 'Total'")
regions_with_most_homicides = regions_with_most_homicides[regions_with_most_homicides["Indicator"].str.startswith("Victims")]
regions_with_most_homicides = regions_with_most_homicides[regions_with_most_homicides["Unit of measurement"].eq("Counts")]
regions_with_most_homicides = regions_with_most_homicides.groupby("Region", as_index=False)["VALUE"].sum()
regions_with_most_homicides = regions_with_most_homicides.sort_values(by="VALUE", ascending=False)
regions_with_most_homicides

                             Region         VALUE
17                            World  9.513397e+06
4   Latin America and the Caribbean  2.904384e+06
14               Sub-Saharan Africa  2.730771e+06
12                    Southern Asia  1.419178e+06
3                    Eastern Europe  6.133761e+05
2                      Eastern Asia  3.840381e+05
8                  Northern America  3.820166e+05
11               South-eastern Asia  3.560990e+05
7                   Northern Africa  2.657808e+05
15                     Western Asia  2.518541e+05
1                      Central Asia  6.295733e+04
16                   Western Europe  4.718013e+04
13                  Southern Europe  3.727337e+04
9                   Northern Europe  3.409429e+04
5                         Melanesia  1.650068e+04
0         Australia and New Zealand  6.933800e+03
10                        Polynesia  5.444053e+02
6                        Micronesia  4.156189e+02

Pergunta 4: Quais países com menor número de homicídios em cada subregião?

In [114]:
least_homicides_by_subregion = countries_df.query("Sex == 'Total'")
least_homicides_by_subregion = least_homicides_by_subregion[least_homicides_by_subregion["Indicator"].eq("Victims of intentional homicide")]
least_homicides_by_subregion = least_homicides_by_subregion[least_homicides_by_subregion["Unit of measurement"].eq("Counts")]
idx = least_homicides_by_subregion.groupby("Subregion")["VALUE"].idxmin()
least_homicides_by_subregion = least_homicides_by_subregion.loc[idx, ["Subregion", "Country", "VALUE"]]
least_homicides_by_subregion = least_homicides_by_subregion.sort_values(by="VALUE", ascending=False)

least_homicides_by_subregion

,Subregion,Country,VALUE
1363,Northern Africa,Morocco,89.0
4602,Central Asia,Turkmenistan,63.0
5453,Eastern Europe,Slovakia,42.0
4841,Australia and New Zealand,New Zealand,35.0
4300,Eastern Asia,"China, Macao Special Administrative Region",1.0
5273,Melanesia,Vanuatu,1.0
1365,Southern Asia,Maldives,1.0
3437,South-eastern Asia,Brunei Darussalam,1.0
1308,Latin America and the Caribbean,Aruba,0.0
2128,Northern America,Bermuda,0.0
1454,Micronesia,Kiribati,0.0
2725,Polynesia,Tuvalu,0.0
1741,Northern Europe,Iceland,0.0
1886,Southern Europe,San Marino,0.0
1779,Sub-Saharan Africa,Saint Helena,0.0
5157,Western Asia,Bahrain,0.0
1752,Western Europe,Liechtenstein,0.0

Pergunta 5: Quais países com menor número de morte de mulheres?

In [101]:
least_female_homicides = countries_df.query("Sex == 'Female'")
least_female_homicides = least_female_homicides[least_female_homicides["Indicator"].eq("Victims of intentional homicide")]
least_female_homicides = least_female_homicides[least_female_homicides["Unit of measurement"].eq("Counts")]
least_female_homicides = least_female_homicides.groupby("Country", as_index=False)["VALUE"].sum()
least_female_homicides = least_female_homicides.sort_values(by="VALUE", ascending=True)
least_female_homicides

                              Country          VALUE
63                           Holy See       0.000000
125             Sao Tome and Principe       0.000000
121         Saint Pierre and Miquelon       0.000000
93                             Monaco       0.000000
92   Micronesia (Federated States of)       1.000000
..                                ...            ...
91                             Mexico   69527.626782
24                             Brazil  122059.786112
154          United States of America  133480.479492
117                Russian Federation  214851.000000
67                              India  383560.786410

[160 rows x 2 columns]

Pergunta 6: Quais as subregiões com maior número de homicídios?

In [102]:
most_homicides_subregion = countries_df.query("Sex == 'Total'")
most_homicides_subregion = most_homicides_subregion[most_homicides_subregion["Indicator"].eq("Victims of intentional homicide")]
most_homicides_subregion = most_homicides_subregion[most_homicides_subregion["Unit of measurement"].eq("Counts")]
most_homicides_subregion = most_homicides_subregion.groupby("Subregion", as_index=False)["VALUE"].sum()
most_homicides_subregion = most_homicides_subregion.sort_values(by="VALUE", ascending=False)
most_homicides_subregion

                          Subregion         VALUE
4   Latin America and the Caribbean  3.784868e+06
12                    Southern Asia  1.883914e+06
3                    Eastern Europe  1.034177e+06
14               Sub-Saharan Africa  9.093686e+05
8                  Northern America  5.722860e+05
2                      Eastern Asia  3.798067e+05
11               South-eastern Asia  3.427134e+05
15                     Western Asia  1.647560e+05
1                      Central Asia  8.100700e+04
16                   Western Europe  7.762556e+04
13                  Southern Europe  5.972846e+04
9                   Northern Europe  5.123598e+04
7                   Northern Africa  4.544800e+04
0         Australia and New Zealand  1.077482e+04
5                         Melanesia  7.288000e+03
10                        Polynesia  2.226281e+02
6                        Micronesia  1.220000e+02

Pergunta 7:  Identifique o país com maior número de homicídios em cada continente em
2020

In [116]:
most_homicides_by_continent = countries_df.query("Year == 2020 & Sex == 'Total'")
most_homicides_by_continent = most_homicides_by_continent[most_homicides_by_continent["Indicator"].eq("Victims of intentional homicide")]
most_homicides_by_continent = most_homicides_by_continent[most_homicides_by_continent["Unit of measurement"].eq("Counts")]
idx = most_homicides_by_continent.groupby("Region")["VALUE"].idxmax()
most_homicides_by_continent = most_homicides_by_continent.loc[idx, ["Region", "Country", "VALUE"]]
most_homicides_by_continent.rename(columns={"Region": "Continent"}, inplace=True)
most_homicides_by_continent = most_homicides_by_continent.sort_values(by="VALUE", ascending=False)

most_homicides_by_continent

     Continent             Country    VALUE
5163  Americas              Brazil  47722.0
5203      Asia               India  40651.0
5275    Africa        South Africa  19972.0
5249    Europe  Russian Federation  10697.0
5153   Oceania           Australia    221.0

Pergunta 8: Qual o país mais violento para as mulheres em 2021?

In [107]:
most_female_homicides_2021 = countries_df.query("Year == 2021 & Sex == 'Female'")
most_female_homicides_2021 = most_female_homicides_2021[most_female_homicides_2021["Indicator"].eq("Victims of intentional homicide")]
most_female_homicides_2021 = most_female_homicides_2021[most_female_homicides_2021["Unit of measurement"].eq("Rate per 100,000 population")]
most_female_homicides_2021 = most_female_homicides_2021.groupby("Country", as_index=False)["VALUE"].sum()
most_female_homicides_2021 = most_female_homicides_2021.sort_values(by="VALUE", ascending=False)
most_female_homicides_2021.head(1)

               Country      VALUE
2  Antigua and Barbuda  10.265149

Pergunta 9: Qual o país com maior valor de 'indicador: Victims of intentional homicide'?

In [105]:
most_victims_of_intentional_homicide = countries_df.query("Sex == 'Total'")
most_victims_of_intentional_homicide = most_victims_of_intentional_homicide[most_victims_of_intentional_homicide["Indicator"].eq("Victims of intentional homicide")]
most_victims_of_intentional_homicide = most_victims_of_intentional_homicide[most_victims_of_intentional_homicide["Unit of measurement"].eq("Counts")]
most_victims_of_intentional_homicide = most_victims_of_intentional_homicide.groupby("Country", as_index=False)["VALUE"].max()
most_victims_of_intentional_homicide = most_victims_of_intentional_homicide.sort_values(by="VALUE", ascending=False)
most_victims_of_intentional_homicide.head(1)

   Country    VALUE
26  Brazil  63788.0

Pergunta 10: Qual a média de homicídios no Brasil nos últimos 10 anos?

In [112]:
brasil_homicides_mean = countries_df.query("Sex == 'Total' & Country == 'Brazil' & Year >= 2012")
brasil_homicides_mean = brasil_homicides_mean[brasil_homicides_mean["Indicator"].eq("Victims of intentional homicide")]
brasil_homicides_mean = brasil_homicides_mean[brasil_homicides_mean["Unit of measurement"].eq("Counts")]
brasil_homicides_mean = brasil_homicides_mean.groupby("Country", as_index=False)["VALUE"].mean()
brasil_homicides_mean = brasil_homicides_mean.sort_values(by="VALUE", ascending=False)
brasil_homicides_mean

  Country    VALUE
0  Brazil  54948.3